create table SensorReferences (
	SensorId INT PRIMARY KEY,
	SensorHeight INT,
	DefaultInstallLocation VARCHAR(50)
);
GO

insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (1, 155, 'Huangbao');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (2, 166, 'Himeville');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (3, 188, 'Bartolomé Masó');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (4, 188, 'San Calixto');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (5, 178, 'Āqchah');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (6, 182, 'Buynaksk');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (7, 185, 'Wakkanai');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (8, 189, 'Jiangzhang');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (9, 189, 'Duanjia');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (10, 181, 'Buaran');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (11, 168, 'Coris');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (12, 187, 'Sunjia');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (13, 175, 'Chakwāl');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (14, 171, 'As Suwaydā’');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (15, 159, 'Gyangqai');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (16, 174, 'Dom Pedro');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (17, 182, 'Quzi');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (18, 190, 'Xiashu');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (19, 186, 'Plan de Ayala');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (20, 158, 'Xiazhai');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (21, 174, 'Halayhay');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (22, 160, 'Puerto Boyacá');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (23, 185, 'Qingshi');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (24, 150, 'Daxinshao');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (25, 170, 'Potęgowo');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (26, 189, 'Kolobovo');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (27, 163, 'Bailadores');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (28, 184, 'Varkaus');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (29, 178, 'Nkurenkuru');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (30, 172, 'Obernai');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (31, 185, 'Blois');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (32, 177, 'Lençóis Paulista');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (33, 164, 'Tasīl');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (34, 178, 'Kota Bharu');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (35, 184, 'Dek’emhāre');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (36, 153, 'Trinidad');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (37, 172, 'Pieksämäki');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (38, 185, 'Obock');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (39, 177, 'Palhais');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (40, 188, 'Diffa');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (41, 174, 'Primorskiy');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (42, 153, 'Pasirpanjang');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (43, 152, 'Bilopillya');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (44, 181, 'Dankunku');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (45, 190, 'Särkisalo');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (46, 162, 'Siquirres');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (47, 158, 'Maslovare');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (48, 154, 'Šenčur');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (49, 173, 'Yemva');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (50, 174, 'Bakersfield');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (51, 151, 'Eindhoven');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (52, 179, 'Leduc');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (53, 172, 'Helvecia');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (54, 154, 'Galtek');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (55, 150, 'Pŭrvomaytsi');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (56, 188, 'Palayan City');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (57, 169, 'Ulaanbaatar');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (58, 177, 'Jaunpiebalga');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (59, 172, 'Kołbaskowo');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (60, 168, 'Negoslavci');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (61, 168, 'Fundación');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (62, 175, 'Mont-Saint-Aignan');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (63, 158, 'Anan');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (64, 189, 'Zakupne');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (65, 179, 'Ratchaburi');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (66, 186, 'Barqueiro');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (67, 170, 'San Jose');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (68, 156, 'Cawayan');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (69, 184, 'Yanggu');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (70, 188, 'Bandung');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (71, 169, 'Putina');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (72, 157, 'Wakema');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (73, 183, 'Huangbizhuang');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (74, 190, 'Arcos');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (75, 168, 'Solna');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (76, 189, 'Santa Rosa');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (77, 151, 'Xiangquan');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (78, 151, 'Guadalupe');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (79, 151, 'Xunhe');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (80, 154, 'Istres');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (81, 151, 'Béboto');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (82, 173, 'Basa');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (83, 186, 'Singosari');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (84, 169, 'Xianglong');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (85, 152, 'Pregradnaya');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (86, 150, 'Dobre Miasto');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (87, 151, 'Danchang');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (88, 150, 'Acobambilla');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (89, 172, 'Bomadi');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (90, 182, 'Khārān');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (91, 159, 'Tourcoing');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (92, 187, 'Angers');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (93, 166, 'Xinjie');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (94, 159, 'Qui Nhon');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (95, 163, 'Cầu Giấy');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (96, 152, 'Emiliano Zapata');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (97, 159, 'Kushtia');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (98, 170, 'Pallisa');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (99, 170, 'Dampek');
insert into SensorReferences (SensorId, SensorHeight, DefaultInstallLocation) values (100, 166, 'Menara');
